# Week 8 (Tue) - Class Activities in CS 315

You are given the file `netflix_top10_countries.tsv` in the folder data, solve the following tasks using it.

**Table of Contents**

1. [Q1: Load the file](#q1)
2. [Q2: Show number of rows](#q2)
3. [Q3: Show column names](#q3)
4. [Q4: Show number of total countries](#q4)
5. [Q5: Show number of TV series](#q5)
6. [Q6: Number of TV series in South Korea](#q6)
7. [Q7: Total weeks of Squid Games in Italy ](#q7)
8. [Q8: Time frame for a given country](#q8)
9. [Q9: Is number of weeks in ranking equal?](#q9)
10. [Q10: Country with fewest weeks](#q10)
11. [Q11: New exercise](#q11)

<a id="q1"></a>
### Q1: Load the file

In [11]:
import pandas as pd
df = pd.read_csv('netflix_top10_countries.tsv',sep='\t')
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2026-10-18,Films,1,Therapy Done Right,NaN,1
1,Argentina,AR,2026-10-18,Films,2,Animals,NaN,2
2,Argentina,AR,2026-10-18,Films,3,Anyone But You,NaN,2
3,Argentina,AR,2026-10-18,Films,4,Doing Life,NaN,3
4,Argentina,AR,2026-10-18,Films,5,Ice Age: Collision Course,NaN,5

<a id="q2"></a>
### Q2: Show number of rows

In [12]:
df.shape[0]

515920

<a id="q3"></a>
### Q3: Show column names

In [13]:
df.columns

Index(['country_name', 'country_iso2', 'week', 'category', 'weekly_rank',
       'show_title', 'season_title', 'cumulative_weeks_in_top_10'],
      dtype='str')

<a id="q4"></a>
### Q4: Show number of total countries

In [14]:
df['country_name'].nunique()

94

<a id="q5"></a>
### Q5: Show number of TV series

In [45]:
df[df["category"] == "TV"]["show_title"].nunique()

3607

<a id="q6"></a>
### Q6: Number of TV series in South Korea

In [46]:
df[(df["country_name"] == "South Korea") & (df["category"] == "TV")]["show_title"].nunique()

486

<a id="q7"></a>
### Q7: Total weeks of Squid Game in Italy

In [47]:
df[(df['country_name'] == 'Italy') & (df['show_title'] == "Squid Game")]["week"].nunique()

29

<a id="q8"></a>
### Q8: Time frame for a given country

Write a function that given a country name prints out the start and end date of their rankings.

Once you have created the function, call it for a few countries to test it.

In [48]:
def show_timeframe(data,country):
    weeks = data[data['country_name']==country]["week"]
    start = weeks.min()
    end = weeks.max()
    print (f"Netflix rankings for {country} exist between {start} and {end}.")

show_timeframe(df,"Chile")

Netflix rankings for Chile exist between 2021-07-04 and 2026-10-18.

<a id="q9"></a>
### Q9: Is number of weeks equal for each country?

The total number of weeks in the rankings is `len(df['week'].unique())`.

The total number of countries is `len(df['country_name'].unique())`.  

For every week, each country has 20 rows.   

If they all stayed the same number of weeks, then the product of these three weeks would be the same as the total number of rows.

In [49]:
df.groupby("country_name")["week"].nunique().nunique()==1

False

We should have expected this to be `False` since we saw in Q8 that Russia stopped being in the rankings after it attacked Ukraine in February 2022.

<a id="q10"></a>
### Q10: Country with fewest weeks

Write a one-liner that will show the country with the fewest weeks in the Netflix rankings

In [50]:
df.groupby("country_name")["week"].nunique().idxmin()

'Russia'

<a id="q11"></a>
### Q11: New exercise

I first create a dicionary, then return the value (score) of the key (rank).

In [ ]:
dictionary = {1:25,2:18,3:15,4:12,5:10,6:8,7:6,8:4,9:2,10:1}
def rank2score (rank):
    return dictionary[rank]

18

Then, I add the score column using the above function.

In [23]:
df["score"] = df["weekly_rank"].apply(rank2score)

In [25]:
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10,score
0,Argentina,AR,2026-10-18,Films,1,Therapy Done Right,NaN,1,25
1,Argentina,AR,2026-10-18,Films,2,Animals,NaN,2,18
2,Argentina,AR,2026-10-18,Films,3,Anyone But You,NaN,2,15
3,Argentina,AR,2026-10-18,Films,4,Doing Life,NaN,3,12
4,Argentina,AR,2026-10-18,Films,5,Ice Age: Collision Course,NaN,5,10

Next, I will reproduce the table in task 2 description.

First, I will filter the show.

In [41]:
lovely = df[df["show_title"] == "Lovely Runner"]

Then, I build the table using `agg()`.

In [43]:
messy_table = lovely.groupby("country_name").agg(total_score = ("score","sum"),total_weeks=("week","nunique"),rankings_list=("weekly_rank",list))

I use `reset_index()` to turn country names into a regular column, then sort countries by their cumulative F1 scores in descending order.

In [51]:
clean_table = messy_table.reset_index().sort_values("total_score", ascending=False)
clean_table

   country_name  total_score  total_weeks          rankings_list
12      Vietnam           75            7  [8, 7, 6, 5, 4, 1, 5]
2     Indonesia           69            7  [9, 7, 6, 7, 4, 1, 5]
3      Malaysia           62            6     [9, 9, 7, 3, 1, 4]
6   Philippines           41            4           [7, 5, 3, 5]
4      Maldives           32            4          [10, 6, 3, 6]
9     Sri Lanka           32            4          [10, 7, 3, 5]
0    Bangladesh           30            3              [5, 4, 6]
1         India           26            3              [8, 4, 5]
7     Singapore           20            4           [9, 7, 5, 9]
11     Thailand           20            3              [7, 8, 5]
8   South Korea           18            3              [9, 7, 5]
10       Taiwan           10            2                 [7, 8]
5      Pakistan            6            1                    [7]

For my final project, our group plans to compare audience responses to wealthy CEO/heir male leads and male leads with ordinary occupations. I selected four K-dramas representing these two categories to explore their global popularity using Netflix Top 10 rankings.

First, I will check whether all four dramas appear in the dataset before comparing their performance across countries.

In [ ]:
dramas = ["Business Proposal", "King the Land", "Hometown Cha-Cha-Cha", "Welcome to Samdal-ri"]

df[df["show_title"].isin(dramas)]["show_title"].unique()

<StringArray>
[       'King the Land',    'Business Proposal', 'Welcome to Samdal-ri',
 'Hometown Cha-Cha-Cha']
Length: 4, dtype: str

All four selected K-dramas are included in the Netflix Top 10 dataset. I will next compare their popularity across countries using the F1 scoring system, where higher rankings receive more points.

In [53]:
business = df[df["show_title"] == "Business Proposal"]

business_messy_table = business.groupby("country_name").agg(
    total_score=("score", "sum"),
    total_weeks=("week", "nunique"),
    rankings_list=("weekly_rank", list)
)
business_clean_table = business_messy_table.reset_index().sort_values("total_score", ascending=False)
business_clean_table.head(10)

,country_name,total_score,total_weeks,rankings_list
19,Indonesia,264,21,"[8, 8, 7, 9, 6, 9, 10, 9, 7, 4, 5, 3, 4, 2, 1,..."
2,Bangladesh,256,29,"[10, 10, 10, 6, 4, 8, 7, 7, 10, 10, 9, 10, 10,..."
26,Malaysia,226,14,"[10, 7, 7, 5, 4, 3, 2, 2, 1, 1, 1, 1, 1, 3]"
57,Vietnam,225,13,"[9, 8, 7, 4, 3, 2, 1, 1, 1, 1, 1, 1, 2]"
41,Philippines,221,13,"[9, 6, 4, 4, 2, 2, 2, 1, 1, 1, 1, 1, 6]"
52,Thailand,216,18,"[10, 9, 9, 8, 8, 6, 10, 8, 7, 3, 2, 2, 1, 1, 1..."
17,Hong Kong,211,12,"[10, 7, 4, 1, 1, 1, 1, 1, 1, 2, 2, 7]"
21,Japan,210,12,"[6, 3, 2, 2, 1, 1, 1, 1, 1, 4, 4, 9]"
47,Singapore,198,13,"[9, 7, 7, 4, 4, 2, 2, 1, 1, 1, 1, 2, 7]"
51,Taiwan,194,12,"[9, 7, 6, 2, 1, 1, 1, 1, 2, 2, 2, 7]"

In [54]:
king = df[df["show_title"] == "King the Land"]


king_messy_table = king.groupby("country_name").agg(
    total_score=("score", "sum"),
    total_weeks=("week", "nunique"),
    rankings_list=("weekly_rank", list)
)
king_clean_table = king_messy_table.reset_index().sort_values("total_score", ascending=False)
king_clean_table.head(10)

,country_name,total_score,total_weeks,rankings_list
18,Indonesia,237,14,"[10, 10, 8, 6, 4, 1, 1, 1, 1, 1, 2, 1, 1, 2]"
24,Malaysia,224,12,"[8, 7, 5, 1, 2, 1, 1, 1, 2, 1, 1, 2]"
45,Singapore,219,11,"[7, 5, 1, 1, 1, 1, 1, 2, 1, 1, 5]"
39,Philippines,209,12,"[10, 8, 3, 2, 2, 2, 1, 1, 1, 1, 1, 5]"
54,Vietnam,190,12,"[10, 9, 6, 2, 3, 1, 1, 2, 2, 1, 1, 5]"
32,Nicaragua,174,17,"[9, 10, 10, 8, 10, 8, 8, 8, 4, 4, 7, 4, 1, 1, ..."
33,Nigeria,167,12,"[9, 6, 3, 2, 2, 3, 3, 3, 5, 2, 1, 6]"
38,Peru,166,12,"[10, 8, 6, 5, 3, 6, 4, 1, 1, 2, 1, 3]"
16,Hong Kong,166,11,"[8, 6, 2, 4, 3, 3, 2, 2, 1, 1, 6]"
15,Honduras,163,12,"[9, 9, 9, 7, 5, 6, 3, 1, 1, 1, 1, 2]"

In [55]:
hometown = df[df["show_title"] == "Hometown Cha-Cha-Cha"]

hometown_messy_table = hometown.groupby("country_name").agg(
    total_score=("score", "sum"),
    total_weeks=("week", "nunique"),
    rankings_list=("weekly_rank", list)
)
hometown_clean_table = hometown_messy_table.reset_index().sort_values("total_score", ascending=False)
hometown_clean_table.head(10)

,country_name,total_score,total_weeks,rankings_list
15,Indonesia,335,20,"[10, 8, 8, 5, 4, 4, 3, 3, 1, 1, 1, 1, 1, 1, 2,..."
35,Thailand,328,31,"[10, 7, 8, 10, 10, 10, 10, 9, 4, 6, 5, 5, 6, 6..."
19,Malaysia,293,17,"[9, 6, 3, 4, 3, 3, 2, 1, 2, 2, 1, 1, 2, 2, 2, ..."
39,Vietnam,278,18,"[10, 10, 6, 5, 6, 4, 3, 2, 1, 2, 2, 1, 1, 2, 2..."
34,Taiwan,276,17,"[9, 6, 5, 7, 4, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, ..."
28,Philippines,270,17,"[10, 9, 6, 5, 5, 4, 2, 2, 1, 1, 1, 1, 2, 3, 3,..."
31,Singapore,233,15,"[8, 9, 6, 5, 3, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2]"
13,Hong Kong,231,16,"[8, 6, 7, 4, 4, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3]"
32,South Korea,178,12,"[9, 7, 5, 3, 2, 1, 2, 2, 2, 3, 3, 2]"
16,Japan,177,13,"[8, 8, 6, 4, 3, 2, 2, 2, 2, 2, 1, 3, 8]"

In [56]:
welcome = df[df["show_title"] == "Welcome to Samdal-ri"]

welcome_messy_table = welcome.groupby("country_name").agg(
    total_score=("score", "sum"),
    total_weeks=("week", "nunique"),
    rankings_list=("weekly_rank", list)
)
welcome_clean_table = welcome_messy_table.reset_index().sort_values("total_score", ascending=False)
welcome_clean_table.head(10)

,country_name,total_score,total_weeks,rankings_list
13,Indonesia,184,12,"[8, 3, 2, 1, 2, 3, 4, 3, 2, 2, 2, 6]"
34,Vietnam,141,11,"[7, 6, 3, 2, 4, 4, 3, 2, 2, 3, 8]"
29,South Korea,137,10,"[7, 3, 2, 3, 3, 3, 3, 2, 2, 9]"
17,Malaysia,133,12,"[9, 5, 5, 1, 3, 6, 5, 4, 4, 4, 3, 9]"
31,Taiwan,108,10,"[10, 7, 2, 5, 6, 3, 3, 6, 4, 3]"
25,Philippines,79,9,"[7, 3, 5, 9, 6, 6, 6, 5, 4]"
28,Singapore,65,9,"[7, 6, 7, 9, 5, 6, 4, 4, 10]"
27,Saudi Arabia,56,9,"[8, 8, 5, 8, 8, 6, 8, 7, 4]"
11,Hong Kong,55,8,"[6, 9, 9, 9, 6, 6, 5, 3]"
18,Maldives,44,8,"[8, 8, 9, 7, 5, 9, 7, 5]"

Although Netflix rankings provide insight into their international popularity, they cannot directly explain audience perceptions of different types of male leads.